In [2]:
# Importar librerías
import numpy as np
import pandas as pd
from sklearn.datasets import load_boston

In [4]:
data = load_boston()
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [15]:
# Establecer semilla para la secuencia de números asleatorios
# Esto garantiza que el experimento se pueda realizar bajo las 
# mismas condiciones, por lo tanto, sea completamente replicable 

# np.random.seed(100)

for _ in range(1, 15):
    samples = np.random.choice(a=15, size=15, replace=True)
    print(samples, ',Num Samples: ' + str(len(samples)) + ',numberUnique: ' + str(len(set(samples))) )

[14 12  0  5  0  9  2  1  6  0  3  7  3 12  9] ,Num Samples: 15,numberUnique: 10
[ 5  2  0 13 11  9 12 13  3 14  6  2  4 13 11] ,Num Samples: 15,numberUnique: 11
[ 1  8  5  1  4  7 12  6  5  8  3 11  5  0  9] ,Num Samples: 15,numberUnique: 11
[13  1  4  3  1  0  6  9 10  9 11  6 12  6 14] ,Num Samples: 15,numberUnique: 11
[ 3 12  3  3  7  2  4  9 10 14  2 14  7  1  2] ,Num Samples: 15,numberUnique: 9
[ 8 13 10 12  3  2  9 11 13 12  2  3  2  7  0] ,Num Samples: 15,numberUnique: 10
[ 6  9 14 11  8 10  2 12 12  1  1  2 11 14  2] ,Num Samples: 15,numberUnique: 9
[ 6 12  2  4  5  1  7  5  4  0 14  1  5 13  9] ,Num Samples: 15,numberUnique: 11
[14 12  0  1  0  4  3  2  7 10  6  3  7 13  2] ,Num Samples: 15,numberUnique: 11
[11  7 12 11  8  5  1 11 10 14 12 11  9  6 13] ,Num Samples: 15,numberUnique: 11
[ 0  9 11  9  2  5  2 14 10  7  1 14 10  1  7] ,Num Samples: 15,numberUnique: 9
[ 8  1  8  2  9  9 10  2  0  3 11  7 10  4  7] ,Num Samples: 15,numberUnique: 10
[ 2  0  1  3  4 10  9  6  5  4 

In [10]:
bootstrappedDF = df.iloc[samples, :]
bootstrappedDF

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS  RAD    TAX  \
3   0.03237   0.0   2.18   0.0  0.458  6.998   45.8  6.0622  3.0  222.0   
10  0.22489  12.5   7.87   0.0  0.524  6.377   94.3  6.3467  5.0  311.0   
2   0.02729   0.0   7.07   0.0  0.469  7.185   61.1  4.9671  2.0  242.0   
3   0.03237   0.0   2.18   0.0  0.458  6.998   45.8  6.0622  3.0  222.0   
14  0.63796   0.0   8.14   0.0  0.538  6.096   84.5  4.4619  4.0  307.0   
14  0.63796   0.0   8.14   0.0  0.538  6.096   84.5  4.4619  4.0  307.0   
6   0.08829  12.5   7.87   0.0  0.524  6.012   66.6  5.5605  5.0  311.0   
13  0.62976   0.0   8.14   0.0  0.538  5.949   61.8  4.7075  4.0  307.0   
4   0.06905   0.0   2.18   0.0  0.458  7.147   54.2  6.0622  3.0  222.0   
1   0.02731   0.0   7.07   0.0  0.469  6.421   78.9  4.9671  2.0  242.0   
14  0.63796   0.0   8.14   0.0  0.538  6.096   84.5  4.4619  4.0  307.0   
3   0.03237   0.0   2.18   0.0  0.458  6.998   45.8  6.0622  3.0  222.0   
1   0.02731   0.0   7.07   0.0  0.469  6.421   78.9  4.9671  2.0  242.0   
4   0.06905   0.0   2.18   0.0  0.458  7.147   54.2  6.0622  3.0  222.0   
8   0.21124  12.5   7.87   0.0  0.524  5.631  100.0  6.0821  5.0  311.0   

    PTRATIO       B  LSTAT  target  
3      18.7  394.63   2.94    33.4  
10     15.2  392.52  20.45    15.0  
2      17.8  392.83   4.03    34.7  
3      18.7  394.63   2.94    33.4  
14     21.0  380.02  10.26    18.2  
14     21.0  380.02  10.26    18.2  
6      15.2  395.60  12.43    22.9  
13     21.0  396.90   8.26    20.4  
4      18.7  396.90   5.33    36.2  
1      17.8  396.90   9.14    21.6  
14     21.0  380.02  10.26    18.2  
3      18.7  394.63   2.94    33.4  
1      17.8  396.90   9.14    21.6  
4      18.7  396.90   5.33    36.2  
8      15.2  386.63  29.93    16.5

In [12]:
for _ in range(1, 15):
    samples = np.random.choice(a=15, size=15, replace=False)
    print(samples, ',Num Samples: ' + str(len(samples)) + ',numberUnique: ' + str(len(set(samples))) )

[ 3  0  5  4  6 14  1  9 12  7 11  2 10 13  8] ,Num Samples: 15,numberUnique: 15
[ 9 14 12  4  7  8  1  6  2 11  3  5 10  0 13] ,Num Samples: 15,numberUnique: 15
[14  9  8  2  0  3  1  7 13  4  6  5 11 10 12] ,Num Samples: 15,numberUnique: 15
[ 8 14 11 12  2  4  9  7  6  3  0 10 13  1  5] ,Num Samples: 15,numberUnique: 15
[ 7  4 11  8 12 10  9  6  2  3  1 14 13  0  5] ,Num Samples: 15,numberUnique: 15
[13  7 12 10  4 11  8  6  3  2  5  1  9 14  0] ,Num Samples: 15,numberUnique: 15
[ 7  1  8  0  2 10 11 12 13  3  6  5  9 14  4] ,Num Samples: 15,numberUnique: 15
[13  9  3  7 12  4 11 10  5  1  8  6 14  2  0] ,Num Samples: 15,numberUnique: 15
[ 5 14 10 11 13  0  6  4  1  7  8  2  3 12  9] ,Num Samples: 15,numberUnique: 15
[ 0  1 10  5  9 11 14  8  3  4  6 13 12  7  2] ,Num Samples: 15,numberUnique: 15
[ 6  9 10 13  5  0  3  2  7  8 11  1 14  4 12] ,Num Samples: 15,numberUnique: 15
[ 8  2  3  1 12  5  4 14 11  6 10  0  9 13  7] ,Num Samples: 15,numberUnique: 15
[13 12  7  8 10  1  2 11  9 

In [16]:
withoutDF = df.iloc[samples, :]
withoutDF.iloc[samples, :]

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS  RAD    TAX  \
6   0.08829  12.5   7.87   0.0  0.524  6.012   66.6  5.5605  5.0  311.0   
0   0.00632  18.0   2.31   0.0  0.538  6.575   65.2  4.0900  1.0  296.0   
5   0.02985   0.0   2.18   0.0  0.458  6.430   58.7  6.0622  3.0  222.0   
5   0.02985   0.0   2.18   0.0  0.458  6.430   58.7  6.0622  3.0  222.0   
8   0.21124  12.5   7.87   0.0  0.524  5.631  100.0  6.0821  5.0  311.0   
8   0.21124  12.5   7.87   0.0  0.524  5.631  100.0  6.0821  5.0  311.0   
8   0.21124  12.5   7.87   0.0  0.524  5.631  100.0  6.0821  5.0  311.0   
1   0.02731   0.0   7.07   0.0  0.469  6.421   78.9  4.9671  2.0  242.0   
8   0.21124  12.5   7.87   0.0  0.524  5.631  100.0  6.0821  5.0  311.0   
8   0.21124  12.5   7.87   0.0  0.524  5.631  100.0  6.0821  5.0  311.0   
8   0.21124  12.5   7.87   0.0  0.524  5.631  100.0  6.0821  5.0  311.0   
3   0.03237   0.0   2.18   0.0  0.458  6.998   45.8  6.0622  3.0  222.0   
3   0.03237   0.0   2.18   0.0  0.458  6.998   45.8  6.0622  3.0  222.0   
13  0.62976   0.0   8.14   0.0  0.538  5.949   61.8  4.7075  4.0  307.0   
1   0.02731   0.0   7.07   0.0  0.469  6.421   78.9  4.9671  2.0  242.0   

    PTRATIO       B  LSTAT  target  
6      15.2  395.60  12.43    22.9  
0      15.3  396.90   4.98    24.0  
5      18.7  394.12   5.21    28.7  
5      18.7  394.12   5.21    28.7  
8      15.2  386.63  29.93    16.5  
8      15.2  386.63  29.93    16.5  
8      15.2  386.63  29.93    16.5  
1      17.8  396.90   9.14    21.6  
8      15.2  386.63  29.93    16.5  
8      15.2  386.63  29.93    16.5  
8      15.2  386.63  29.93    16.5  
3      18.7  394.63   2.94    33.4  
3      18.7  394.63   2.94    33.4  
13     21.0  396.90   8.26    20.4  
1      17.8  396.90   9.14    21.6